version: '3'

services:
  front:
    build:
      dockerfile: Dockerfile
      context: .
    image: ippolab/athena-frontend
    container_name: athena_front
    env_file:
      - .env
    ports:
      - "8080:80"
